### ISSUE TITLE
stamped_js template invalid with magento 2.2.5

### ISSUE THREAD

**Issue by metizror** [Stamped-io/Magento-v2.x#1]
https://www.awesomescreenshot.com/image/3685601/9f48d9554409e351b8b68ab7d1a0eac5

**Comment by metizror** [comment]
> 
> 
> https://www.awesomescreenshot.com/image/3685601/9f48d9554409e351b8b68ab7d1a0eac5

**Comment by tommyong** [comment]
This has been resolved in the latest updates.
