### ISSUE TITLE
PHP 7.4 error

### ISSUE THREAD

**Issue by jasuten** [Stamped-io/Magento-v2.x#10]
Hi,

We are getting the following error with the extension when compiling Magento with PHP 7.4:
`  Deprecated Functionality: Cannot use "parent" when current class scope has no parent in /app/code/Stamped
  /Core/Controller/AbstractController/CoreLoader.php on line 37`

**Comment by hueiyik** [comment]
![image](https://user-images.githubusercontent.com/38139860/99035153-f2589080-25b9-11eb-9600-6b7794bdcb28.png)

**Comment by tommyong** [comment]
An update has been rolled out:
https://github.com/Stamped-io/Magento-v2.x/blob/master/Stamped/Core/Controller/AbstractController/CoreLoader.php

Please let us know if it's working well.

**Comment by hueiyik** [comment]
Hi

Where can I download the update?

Thanks

________________________________

**Comment by tommyong** [comment]
You can get the update on the above link
