### ISSUE TITLE
Photo Loading Issues

### ISSUE THREAD

**Issue by eneskirca** [Stamped-io/Magento-v2.x#11]
Stamped reviews(photos and script) loading before fotoroma gallery javascripts, I have 70 reviews with images for some products so product gallery delay until fully loaded stamped reviews

**Comment by tommyong** [comment]
@eneskirca Can you provide us your store URL?

**Comment by eneskirca** [comment]
@tommyong https://www.ottasilver.com/

**Comment by eneskirca** [comment]
@tommyong Did you handle the problem, What is the expected solution time?

**Comment by tommyong** [comment]
We weren't able to replicate this issue on your site, can you take a recording so we can assists with this?

**Comment by eneskirca** [comment]
this test without stamped reviews;
https://gtmetrix.com/reports/www.ottasilver.com/Bea7TKxe/
and this test is without it
https://gtmetrix.com/reports/www.ottasilver.com/XCboteNC/

you can see there is a delay for interactive times I think this is because of product gallery ajax delaying because of stamped ajax or images 

by the way it is not like that in M1 , if you can visit ottasilver.co.uk that is still M1 you will see there is no delay product gallery but you need to visit united kingdom IP to avoid redirection , use vpn

**Comment by eneskirca** [comment]
https://imgur.com/a/QeORIQr

**Comment by tommyong** [comment]
@eneskirca it seems that lazyloading option was disabled for your account, we've enabled it.
