### ISSUE TITLE
Regarding Extesnions

### ISSUE THREAD

**Issue by InfoMicrowebies** [Stamped-io/Magento-v2.x#2]
I have installed this extensions on my website (magento ver 2.2.6) after installation many js error in console.
because of this script - <script async onload="stampedInit()" type="text/javascript" src="https://cdn-stamped-io.azureedge.net/files/widget.min.js"></script> 
So can you please provide updated script for the same magento version.
Find attached screenshots for more clarification 
![2019-01-04_13-53_elegant star tape in hair](https://user-images.githubusercontent.com/41819472/50679133-22cb5d00-1028-11e9-9ea0-9dcf66e19304.jpg)

**Comment by tommyong** [comment]
This has been fixed with the latest updates.
