### ISSUE TITLE
adding stamped.io to whiltelist in CSP module magento2.3.5

### ISSUE THREAD

**Issue by Asma-Hawari** [Stamped-io/Magento-v2.x#7]
Hi , 
I'm working on Magento 2.3.5 and I have to whitelist your domain in csp_whitelist.xml so it can work ( due to a newly added module named csp in magento2.3.5)
I added this line to <policy id="connect-src"> <value id="stamped" type="host">*.stamped.io</value>
but it's not working , do you have any idea why ? 
did I add the. wrong host for your extension ?? 
<img width="1440" alt="Screen Shot 2020-06-03 at 1 56 10 PM" src="https://user-images.githubusercontent.com/42111177/83629097-3292fc00-a5a2-11ea-8c18-f0ecde79bea0.png">

**Comment by tommyong** [comment]
Likely due to the “Id”.

**Comment by Asma-Hawari** [comment]
i don't think so ! 
i will attach the images from the server , please reply asap 
thank you !
<img width="1440" alt="Screen Shot 2020-06-27 at 11 04 34 AM" src="https://user-images.githubusercontent.com/42111177/85917846-5f1afa80-b866-11ea-81dc-5aa7041f7e88.png">
<img width="1209" alt="Screen Shot 2020-06-27 at 11 05 06 AM" src="https://user-images.githubusercontent.com/42111177/85917849-6215eb00-b866-11ea-9acd-816ce061216d.png">
