### ISSUE TITLE
Mage::app() in Helper

### ISSUE THREAD

**Issue by magenizr** [Stamped-io/Magento-v2.x#8]
Mage::app() won't work if https://github.com/Stamped-io/Magento-v2.x/blob/master/Stamped/Core/Helper/Data.php#L466 returns false.

https://github.com/Stamped-io/Magento-v2.x/blob/5140c0317f3466554442bfac2244ffb9c1f24602/Stamped/Core/Helper/Data.php#L468

Credits @portchris

**Comment by tommyong** [comment]
This usually means that the store URL in settings is empty, you do need to set the store URL.
